platform :ios, '8.0'

pod "MSColorPicker", :path => "../"

abstract_target 'Demo' do
    
    pod 'MSColorPicker', :path => '../'
    
    target 'MSColorPickerDemo'
    target 'MSColorPickerDemoTests'
    
end

